### ISSUE TITLE
功能请求-更强的motd自定义

### ISSUE THREAD

**Issue by lilingfengdev** [RTAkland/YeeeesMOTD#7]
非常好的插件，但我希望可以做出更好看的motd

像这个插件 https://www.spigotmc.org/resources/advancednmotd-let-your-motd-smile.58677/ 支持左边一行motd,悬浮motd,更改版本描述之类的

谢谢

**Comment by RTAkland** [comment]
需求的图片示例有吗， 另外插件可以更改版本描述，见[虚假版本协议以及协议描述](https://github.com/RTAkland/YeeeesMOTD?tab=readme-ov-file#%E8%99%9A%E5%81%87%E7%89%88%E6%9C%AC%E5%8D%8F%E8%AE%AE%E4%BB%A5%E5%8F%8A%E5%8D%8F%E8%AE%AE%E6%8F%8F%E8%BF%B0), 麻烦留下想要实现的效果的图片哦😊

**Comment by RTAkland** [comment]
你的意思是实现这种效果吗![image](https://github.com/user-attachments/assets/3a3b71c6-b702-4ab5-90da-ad3b62a8ac4d) 在右上角显示彩色的Join字样, 然后显示出在线玩家列表嘛

**Comment by RTAkland** [comment]
在1.3.9的版本中可以使用MiniMessage的语法来自定义协议名称了，并且添加了两个变量`<onlinePlayer>` 和 `<maxPlayer>`来获取到最大玩家数和在线玩家数

**Comment by RTAkland** [comment]
另外在左侧显示出`Connect >>>`字样是自定义版本信息并且添加了很多空格使文本超出了图标, 你可以在config.json中参考一下配置来实现这个效果
```json
  "fakeProtocol": {
    "enabled": true,
    "protocolNumberPool": [],
    "protocolNamePool": [
      "<yellow>快<green>来<blue>玩~                                                             <green>测试 <yellow><bold>[<onlinePlayer>/<maxPlayer>]"
    ],
    "alwaysInvalidProtocolNumber": true
  },
```

主要注意第五行，如果你要修改文字的话记得自己测试并且控制好空格的间距哦~

**Comment by RTAkland** [comment]
另外悬浮文本是用玩家列表实现的，你可以把config.json中的`clearSamplePlayer`改为false以便不清除玩家列表，然后修改username.txt清空这个文件然后修改里面的内容，里面每一行就是悬浮文本的一行， 例如
```txt
你好
这是一行测试
114514
1919810
这是一个超极长的测试文本用于测试在线玩家列表
```

这里有5行你要把config.json内的
```json
  "fakeSamplePlayer": {
    "enabled": true,
    "fakePlayersCount": 5
  },
```

`enabled`改为true然后`fakePlayersCount`改成username.txt中的行数不然的话会重复的哦

**Comment by aeroidesdev** [comment]
谢谢
