### ISSUE TITLE
modrinth下不了了

### ISSUE THREAD

**Issue by Azusa-mikan** [RTAkland/YeeeesMOTD#9]
![image](https://github.com/user-attachments/assets/15feee37-eb9f-46b8-9935-0687c5342aae)

**Comment by RTAkland** [comment]
我去查看一下是什么问题

**Comment by RTAkland** [comment]
感觉是modrinth那边的问题，我的modrinth账号登陆不上了

**Comment by RTAkland** [comment]
确认了就是modrinth那边的问题，任何在上面的模组/插件打开都是404，你的服务端是什么平台的我直接把文件放在这里

**Comment by RTAkland** [comment]
https://www.bilibili.com/video/BV1JfqhYsE1L

**Comment by RTAkland** [comment]
[YeeeesMOTD-1.4.1-all.zip](https://github.com/user-attachments/files/18113983/YeeeesMOTD-1.4.1-all.zip)
这是所有平台的jar解压后找到你对应服务端的jar就行了

**Comment by Azusa-mikan** [comment]
谢谢啦
